from typing import Protocol, Optional, List, Dict, Any
from app.models import UserModel, RealEstateObjectModel, ConversationModel, MessageModel

class DataRepository(Protocol):
    def get_user_by_username(self, username: str) -> Optional[UserModel]: ...
    def get_user_by_id(self, user_id: str) -> Optional[UserModel]: ...
    def create_user(self, user: UserModel) -> UserModel: ...

    def get_properties_for_user(self, user_id: str) -> List[RealEstateObjectModel]: ...
    def get_property_by_id_and_user(self, property_id: str, user_id: str) -> Optional[RealEstateObjectModel]: ...
    def get_property_by_id(self, property_id: str) -> Optional[RealEstateObjectModel]: ...
    def create_property(self, property: RealEstateObjectModel) -> RealEstateObjectModel: ...
    def update_property(self, property: RealEstateObjectModel) -> RealEstateObjectModel: ...
    def delete_property(self, property_id: str, user_id: str) -> bool: ...

    def get_conversations_for_property(self, property_id: str) -> List[ConversationModel]: ...
    def get_conversation_by_id_and_user(self, conversation_id: str, user_id: str) -> Optional[ConversationModel]: ...
    def create_conversation(self, conversation: ConversationModel) -> ConversationModel: ...
    def update_conversation(self, conversation: ConversationModel) -> ConversationModel: ...
    def delete_conversation(self, conversation_id: str, user_id: str) -> bool: ...

    def add_message(self, message: MessageModel) -> MessageModel: ...
